name: Fetch and Translate Todays Darling

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-and-translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 selenium requests
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Scrape and translate
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        run: |
          python .github/scripts/fetch_translate.py

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add translations/ originals/
          git commit -m "Update translation for $(date +'%Y-%m-%d')" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
