name: Generate Particle JSON

on:
  workflow_run:
    workflows: ["fetch_translate"]
    types:
      - completed

jobs:
  generate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run generator
        run: python3 scripts/generate_particle_json.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.json translation.json
          git commit -m "Daily Particle update"
          git push
